# Generated by Django 4.0.3 on 2022-04-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(max_length=66),
        ),
    ]
